### ISSUE TITLE
undefined method `inject_into_module' when running the generator

### ISSUE THREAD

**Issue by zedtux** [CyberDeck/devise-fido-u2f#2]
As described in the `README.md` file, I have added this gem to my Rails project and I'm now running the generator, but it raises the following error:

```
/devise-fido-u2f/lib/generators/devise_fido_usf/install_generator.rb:31:in `block in add_application_helper': undefined method `inject_into_module' for #<DeviseFidoUsf::Generators::InstallGenerator:0x0000000b1e86a0> (NoMethodError)
	from /bundle/gems/thor-0.19.1/lib/thor/actions.rb:194:in `block in in_root'
	from /bundle/gems/thor-0.19.1/lib/thor/actions.rb:184:in `block in inside'
	from /usr/local/lib/ruby/2.2.0/fileutils.rb:127:in `chdir'
	from /usr/local/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
	from /bundle/gems/thor-0.19.1/lib/thor/actions.rb:184:in `inside'
	from /bundle/gems/thor-0.19.1/lib/thor/actions.rb:194:in `in_root'
	from /devise-fido-u2f/lib/generators/devise_fido_usf/install_generator.rb:30:in `add_application_helper'
	from /bundle/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /bundle/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /bundle/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /bundle/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /bundle/gems/railties-4.2.2/lib/rails/generators.rb:157:in `invoke'
	from /bundle/gems/railties-4.2.2/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /bundle/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
	from /bundle/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
	from /bundle/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /bundle/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
	from /bundle/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /bundle/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /bundle/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /bundle/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /bundle/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by zedtux** [comment]
My bad, this is because my version of the thor gem is lower than 0.20.0.
